version: "3"
services:
  web:
    image: vmmx
    build: .
    ports:
      - 8000:80

  dev:
    image: vmmx-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/work
    command: npm start
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
